name: Build and deploy docker image
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
#         with:
#           repository: 'go-gitea/gitea'
#           ref: 'v1.20.2'
      
      - name: Origin version
        id: origin-version
        run: curl -sL https://api.github.com/repos/go-gitea/gitea/releases/latest | jq -r ".tag_name"
      
      - name: Local version
        id: local-version
        uses: reloc8/action-latest-release-version@1.0.0

      - name: Test
        run: |
          echo ${{ steps.origin-version.outputs.latest-release }}
          echo ${{ steps.local-version.outputs.latest-release }}
      
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
      
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           platforms: linux/amd64,linux/386,linux/arm64,linux/arm,linux/arm/v6
#           push: true
#           tags: zyxd/gitea:latest
