name: Build and deploy docker image
# on:
#   schedule:
#     - cron: "30 17 * * *"
on: [push]
env:
  ORIGIN_URL: https://api.github.com/repos/go-gitea/gitea/releases/latest
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set github tag
        id: github-tag
        run: echo "TAG=`curl -sL $ORIGIN_URL | jq -r ".tag_name"`" >> "$GITHUB_OUTPUT"
    
      - name: Set docker tag
        id: docker-tag
        run: echo "TAG=`echo ${{ steps.github-tag.outputs.TAG }} | sed 's/^v//'`" >> "$GITHUB_OUTPUT"

      - name: Print
        run: |
          echo "github tag: ${{ steps.github-tag.outputs.TAG }}"
          echo "docker tag: ${{ steps.docker-tag.outputs.TAG }}"

      - name: Test
        # if: curl --silent -f -lSL https://hub.docker.com/v2/repositories/zyxd/gitea/tags/${{ steps.docker-tag.outputs.TAG }}
        shell: bash
        run: |
          if [ curl --silent -f -lSL https://hub.docker.com/v2/repositories/zyxd/gitea/tags/${{ steps.docker-tag.outputs.TAG }} ]; then
            echo "Success"
          else
            echo "Failed"
          fi

      # - name: Check out repository code
      #   uses: actions/checkout@v3
      #   with:
      #     repository: 'go-gitea/gitea'
      #     ref: ${{ steps.github-tag.outputs.TAG }}
      
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     platforms: linux/arm64,linux/arm/v7,linux/arm/v6,linux/amd64,linux/i386
      #     push: true
      #     tags: zyxd/gitea:latest,zyxd/gitea:${{ steps.docker-tag.outputs.TAG }}
