name: Deploy docker image
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: 'go-gitea/gitea'
          ref: 'v1.20.2'

      - name: List files in the repository
        run: ls ${{ github.workspace }}
