name: Build and deploy docker image
on: [push]
env:
  ORIGIN_URL: https://api.github.com/repos/go-gitea/gitea/releases/latest
  MIRROR_URL: https://api.github.com/repos/zyxd/gitea/releases/latest
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest tag
        id: latest_tag
        uses: jacobtomlinson/gha-get-docker-hub-tags@0.1.1
        with:
          org: 'gitea'
          repo: 'gitea'

      - name: Check outputs
        run: |
          echo "Latest Image Tag - ${{ steps.latest_tag.outputs.tag }}"
      
#       - name: Check origin version
#         id: origin-version
#         run: echo "VERSION=`curl -sL $ORIGIN_URL | jq -r ".tag_name"`" >> "$GITHUB_OUTPUT"
        
#       - name: Check mirror version
#         id: mirror-version
#         run: echo "VERSION=`curl -sL $MIRROR_URL | jq -r ".tag_name"`" >> "$GITHUB_OUTPUT"

#       - name: Version
#         run: |
#           echo ${{ steps.origin-version.outputs.VERSION }}
#           echo ${{ steps.mirror-version.outputs.VERSION }}
      
#       - name: Release
#         uses: softprops/action-gh-release@v1
#         with:
#           tag_name: ${{ steps.origin-version.outputs.VERSION }}
      
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
      
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           platforms: linux/amd64,linux/386,linux/arm64,linux/arm,linux/arm/v6
#           push: true
#           tags: zyxd/gitea:latest
