name: Build and deploy docker image
# on:
#   schedule:
#     - cron: "30 17 * * *"
on: [push]
env:
  GITHUB_URL: https://api.github.com/repos/go-gitea/gitea/releases/latest
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      github-tag: ${{ steps.github-tag.outputs.tag }}
      docker-tag: ${{ steps.docker-tag.outputs.tag }}
      docker-exists: ${{ steps.docker-exists.outputs.exists }}
    steps:
      - name: Check github tag
        id: github-tag
        run: echo "tag=`curl -sL $GITHUB_URL | jq -r ".tag_name"`" >> "$GITHUB_OUTPUT"
    
      - name: Set docker tag
        id: docker-tag
        run: echo "tag=`echo ${{ steps.github-tag.outputs.TAG }} | sed 's/^v//'`" >> "$GITHUB_OUTPUT"

      - name: Check if docker image already exists
        id: docker-exists
        shell: bash
        env:
          DOCKER_URL: https://hub.docker.com/v2/repositories/zyxd/gitea/tags/${{ steps.docker-tag.outputs.TAG }}
        run: |
         if [ `curl --silent -f -lSL $DOCKER_URL` ]; then
           echo "exists=true" >> "$GITHUB_OUTPUT"
         else
           echo "exists=false" >> "$GITHUB_OUTPUT"
         fi

  deploy:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.docker-exists == 'false' }}
    steps:
      - name: Test
        run: |
          echo "${{needs.check.outputs.github-tag}}"
          echo "${{needs.check.outputs.docker-tag}}"
          echo "${{needs.check.outputs.docker-exists}}"

      # - name: Check out repository code
      #   uses: actions/checkout@v3
      #   with:
      #     repository: 'go-gitea/gitea'
      #     ref: ${{ steps.github-tag.outputs.TAG }}
      
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     platforms: linux/arm64,linux/arm/v7,linux/arm/v6,linux/amd64,linux/i386
      #     push: true
      #     tags: zyxd/gitea:latest,zyxd/gitea:${{ steps.docker-tag.outputs.TAG }}
