name: Build and deploy docker image
on: [push]
env:
  ORIGIN_URL: https://api.github.com/repos/go-gitea/gitea/releases/latest
  MIRROR_URL: https://api.github.com/repos/zyxd/gitea/releases/latest
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set github tag
        id: github-tag
        run: echo "TAG=`curl -sL $ORIGIN_URL | jq -r ".tag_name"`" >> "$GITHUB_OUTPUT"
    
      - name: Set docker tag
        id: docker-tag
        run: echo "TAG=`echo ${{ steps.github-tag.outputs.TAG }} | sed 's/^v//'`" >> "$GITHUB_OUTPUT"

      - name: Print
        run: |
          echo ${{ steps.github-tag.outputs.TAG }}
          echo ${{ steps.docker-tag.outputs.TAG }}

#       - name: Check out repository code
#         uses: actions/checkout@v3
#         with:
#           repository: 'go-gitea/gitea'
#           ref: ${{ steps.origin-version.outputs.TAG }}
      
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
      
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           platforms: linux/386,linux/arm,linux/arm/v6
#           push: true
#           tags: zyxd/gitea:latest
