name: Build and deploy docker image
on:
  workflow_dispatch:
env:
  GITHUB_URL: https://api.github.com/repos/go-gitea/gitea/releases/latest
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      github-tag: ${{ steps.github-tag.outputs.tag }}
      docker-tag: ${{ steps.docker-tag.outputs.tag }}
      docker-exists-normal: ${{ steps.docker-exists-normal.outputs.exists }}
      docker-exists-rootless: ${{ steps.docker-exists-rootless.outputs.exists }}
    steps:
      - name: Check github tag
        id: github-tag
        run: echo "tag=`curl -sL $GITHUB_URL | jq -r ".tag_name"`" >> "$GITHUB_OUTPUT"
    
      - name: Set docker tag
        id: docker-tag
        run: echo "tag=`echo ${{ steps.github-tag.outputs.TAG }} | sed 's/^v//'`" >> "$GITHUB_OUTPUT"

      - name: Check that docker normal image already exists
        id: docker-exists-normal
        shell: bash
        env:
          DOCKER_URL: https://hub.docker.com/v2/repositories/zyxd/gitea/tags/${{ steps.docker-tag.outputs.TAG }}
        run: |
         if [ `curl --silent -f -lSL $DOCKER_URL` ]; then
           echo "exists=true" >> "$GITHUB_OUTPUT"
         else
           echo "exists=false" >> "$GITHUB_OUTPUT"
         fi

      - name: Check that docker rootless image already exists
        id: docker-exists-rootless
        shell: bash
        env:
          DOCKER_URL: https://hub.docker.com/v2/repositories/zyxd/gitea/tags/${{ steps.docker-tag.outputs.TAG }}-rootless
        run: |
         if [ `curl --silent -f -lSL $DOCKER_URL` ]; then
           echo "exists=true" >> "$GITHUB_OUTPUT"
         else
           echo "exists=false" >> "$GITHUB_OUTPUT"
         fi

  build-normal:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.docker-exists-normal == 'false' }}
    strategy:
      matrix:
        architecture: [arm64, arm/v7, arm/v6, amd64, i386]
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: 'go-gitea/gitea'
          ref: ${{ needs.check.outputs.github-tag }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: zyxd/gitea:latest,zyxd/gitea:${{ needs.check.outputs.docker-tag }}
          platforms: linux/${{ matrix.architecture }}
